# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0004_auto_20171104_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
    ]
