# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('base_url', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('type', models.PositiveIntegerField(choices=[(1, b'E-Commerce'), (2, b'SaaS'), (99, b'Other')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.PositiveIntegerField(choices=[(1, b'E-Commerce'), (2, b'SaaS'), (99, b'Other')])),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_events', to='core.Campaign')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Campaign Event',
                'verbose_name_plural': 'Campaign Events',
            },
        ),
        migrations.CreateModel(
            name='RecordedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=256)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_events', to='core.CampaignEvent')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Recorded Event',
                'verbose_name_plural': 'Recorded Evente',
            },
        ),
        migrations.CreateModel(
            name='StandardEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.PositiveIntegerField(choices=[(1, b'E-Commerce'), (2, b'SaaS'), (99, b'Other')])),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Standard Event',
                'verbose_name_plural': 'Standard Events',
            },
        ),
    ]
