# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171108_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignevent',
            name='code',
        ),
        migrations.RemoveField(
            model_name='standardevent',
            name='code',
        ),
    ]
