# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171108_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=1024)),
                ('icon', models.ImageField(upload_to='notification_icons')),
                ('url', models.TextField()),
                ('number_sent', models.PositiveIntegerField(default=0)),
                ('number_opened', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Event Notificationt',
                'verbose_name_plural': 'Event Notifications',
            },
        ),
        migrations.CreateModel(
            name='RecordedEventToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Recorded Event Token',
                'verbose_name_plural': 'Recorded Event Tokens',
            },
        ),
        migrations.AddField(
            model_name='recordedevent',
            name='page_title',
            field=models.CharField(default='page_title', max_length=1204),
        ),
        migrations.AddField(
            model_name='recordedevent',
            name='url',
            field=models.TextField(default='http://placeholder'),
        ),
        migrations.RemoveField(
            model_name='recordedevent',
            name='token',
        ),
        migrations.AlterUniqueTogether(
            name='recordedevent',
            unique_together=set([('event', 'url')]),
        ),
        migrations.AddField(
            model_name='recordedeventtoken',
            name='recorded_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.RecordedEvent'),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='recorded_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.RecordedEvent'),
        ),
        migrations.AlterUniqueTogether(
            name='recordedeventtoken',
            unique_together=set([('recorded_event', 'token')]),
        ),
    ]
