# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171109_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('external_plan_name', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='usd', max_length=5)),
                ('max_campaigns', models.PositiveIntegerField(default=1)),
                ('max_events_per_campaign', models.PositiveIntegerField(default=3)),
                ('max_notifications_per_event', models.PositiveIntegerField(default=1000)),
                ('max_notifications_per_day', models.PositiveIntegerField(default=3)),
                ('powered_by_link_hidden', models.BooleanField(default=False)),
                ('custom_notification_icon', models.BooleanField(default=False)),
                ('modify_notification_url', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.AlterModelOptions(
            name='eventnotification',
            options={'ordering': ['-date_created'], 'verbose_name': 'Event Notification', 'verbose_name_plural': 'Event Notifications'},
        ),
    ]
