# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171110_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedeventtoken',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordedeventtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
