# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171111_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignevent',
            options={'ordering': ['order'], 'verbose_name': 'Campaign Event', 'verbose_name_plural': 'Campaign Events'},
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
