# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbraintree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btplan',
            name='trial_duration_unit',
            field=models.CharField(default='month', max_length=5),
        ),
    ]
