# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbraintree', '0002_auto_20171122_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcurrentsubscription',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2017, 11, 22, 21, 4, 50, 298000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btcurrentsubscription',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
