# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbraintree', '0003_auto_20171122_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btcurrentsubscription',
            options={'verbose_name': 'Braintree Subscription', 'verbose_name_plural': 'Braintree Subscriptions'},
        ),
        migrations.AlterField(
            model_name='btcurrentsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btsubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
