# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbraintree', '0004_auto_20171122_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcurrentsubscription',
            name='billing_period_end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 22, 24, 32, 862000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btcurrentsubscription',
            name='billing_period_start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 22, 24, 43, 982000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btcurrentsubscription',
            name='expire_at_period_end',
            field=models.BooleanField(default=True),
        ),
    ]
