# -*- coding: utf-8 -*-

CAMPAIGN_TYPE_ECOMMERCE = 1
CAMPAIGN_TYPE_SAAS = 2
CAMPAIGN_TYPE_OTHER = 99

CAMPAIGN_TYPE_CHOICES=(
    (CAMPAIGN_TYPE_ECOMMERCE, 'E-Commerce'),
    (CAMPAIGN_TYPE_SAAS, 'SaaS'),
    (CAMPAIGN_TYPE_OTHER, 'Other'),
)