# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_apikey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
